"""Write the generated pages of the docs site in docs/.

    python3 build_docs.py           # rewrite the generated pages
    python3 build_docs.py --check   # exit 1 if any is out of date

The site is docsify: docs/index.html renders the Markdown files in docs/ in
the browser, so GitHub Pages serves the folder as it is (docs/.nojekyll
turns Jekyll off). Most pages, and _sidebar.md, are edited in place. This
script writes the two that come from elsewhere:

- limitations.md: copied from LIMITATIONS.md.
- api.md: the public API, from the package's docstrings and CLI help.
"""

import argparse
import inspect
import re
import subprocess
import sys
from enum import Enum
from pathlib import Path

import omnes_formae as package

ROOT = Path(__file__).parent
DOCS = ROOT / "docs"
NOTE = (
    "<!-- Generated by build_docs.py from {source}. Edit that, then rerun it. -->"
    "\n\n"
)
DISCLOSURE = (
    "\n---\n\nAI disclosure: written with an AI assistant (Claude, by Anthropic), "
    "directed\nand reviewed by njg4ne.\n"
)


def copied(source: str) -> str:
    text = (ROOT / source).read_text(encoding="utf-8")
    return NOTE.format(source=source) + text.replace("](docs/", "](")


def docstring(obj) -> str:
    """A docstring as Markdown: doctests fenced, Args: as a list."""
    out, in_code, in_args = [], False, False
    for line in (inspect.getdoc(obj) or "").splitlines():
        stripped = line.strip()
        if stripped.startswith(">>>"):
            if not in_code:
                out.append("```python")
                in_code = True
            out.append(stripped)
            continue
        if in_code and stripped:  # doctest output
            out.append(stripped)
            continue
        if in_code:
            out.append("```")
            in_code = False
        if stripped in ("Args:", "Returns:"):
            in_args = stripped == "Args:"
            out += [f"**{stripped[:-1]}**", "", ""]
        elif in_args and re.match(r"^    \w+: ", line):
            name, desc = stripped.split(": ", 1)
            out.append(f"- `{name}`: {desc}")
        elif line.startswith("    ") and stripped:
            if out[-1]:
                out[-1] += " " + stripped  # continuation of a list item
            else:
                out[-1] = stripped  # the text under Returns:
        else:
            in_args = in_args and bool(stripped)
            out.append(stripped if line.startswith("    ") else line)
    if in_code:
        out.append("```")
    return "\n".join(out) + "\n"


def enum_table(cls: type[Enum]) -> str:
    """Members, codes and the comments beside or above them in the source."""
    comments, above = {}, ""
    for line in inspect.getsource(cls).splitlines():
        if line.strip().startswith("#"):
            above = line.strip("# ")  # covers the members below it
        elif match := re.match(r'^\s+(\w+) = "\w+"(?:\s+# (.*))?$', line):
            comments[match[1]] = " ".join(filter(None, [above, match[2]]))
    rows = ["| Member | Code | Note |", "|---|---|---|"]
    for member in cls:
        note = comments.get(member.name, "")
        rows.append(f"| `{member.name}` | `{member.value}` | {note} |")
    return "\n".join(rows) + "\n"


MODULE_PREFIX = re.compile(r"\b[\w.]+\.(?=\w)")  # "pathlib.Path" -> "Path"


def python_signature(name: str, func) -> str:
    """The signature as code, one parameter per line, with no local paths."""
    sig = inspect.signature(func)
    params = []
    for param in sig.parameters.values():
        text = str(param).replace(repr(package.WHITAKER_DIR), "WHITAKER_DIR")
        params.append("    " + MODULE_PREFIX.sub("", text) + ",")
    result = MODULE_PREFIX.sub("", inspect.formatannotation(sig.return_annotation))
    return f"{name}(\n" + "\n".join(params) + f"\n) -> {result}"


def cli_help(module: str) -> str:
    result = subprocess.run(
        [sys.executable, "-m", module, "--help"],
        capture_output=True, text=True, check=True, cwd=ROOT,
    )
    return f"```text\n{result.stdout.rstrip()}\n```\n"


def api() -> str:
    parts = [
        NOTE.format(source="the package's docstrings"),
        "# API reference\n\n",
        "Everything below is importable from `omnes_formae`:\n\n",
        "```python\nfrom omnes_formae import get_latin_forms, PartOfSpeech\n```\n\n",
        "See [Looking up one word](lookup.md) for examples and the keys of each row.\n",
    ]
    functions = ["get_latin_forms", "write_forms", "iter_forms"]
    enums = ["PartOfSpeech", "Frequency", "Age"]
    assert set(package.__all__) == {*functions, *enums, "WHITAKER_DIR"}, package.__all__

    parts.append("\n## Functions\n")
    for name in functions:
        func = getattr(package, name)
        signature = python_signature(name, func)
        parts.append(f"\n### `{name}`\n\n```python\n{signature}\n```\n\n")
        parts.append(docstring(func))

    parts.append("\n## Codes\n")
    for name in enums:
        cls = getattr(package, name)
        parts.append(f"\n### `{name}`\n\n{docstring(cls)}\n{enum_table(cls)}")
        if name == "Frequency":
            parts.append(f"\n`Frequency.rank`: {docstring(cls.rank).strip()}\n")
    parts.append(
        "\nEach member is a `str` equal to its code: `PartOfSpeech.VERB == \"V\"`, "
        "and `str()` and JSON give the code.\n"
    )

    parts.append(
        "\n## `WHITAKER_DIR`\n\n"
        "The folder of bundled Whitaker data files (`DICTLINE.GEN`, `INFLECTS.LAT`, "
        "`UNIQUES.LAT`), inside the installed package. It is the default `data_dir` "
        "of every function above; pass another folder with the same files to use "
        "other data.\n"
    )

    parts.append("\n## Command line\n\nWrite the flat list of forms:\n\n")
    parts.append(cli_help("omnes_formae"))
    parts.append(
        "\nOnce the package is installed, `omnes-formae` runs the same command.\n\n"
        "Check the list and the lookup, for example after editing the data:\n\n"
    )
    parts.append(cli_help("omnes_formae.verify"))
    parts.append(DISCLOSURE)
    return "".join(parts)


def pages() -> dict[Path, str]:
    return {
        DOCS / "limitations.md": copied("LIMITATIONS.md"),
        DOCS / "api.md": api(),
    }


def main() -> None:
    parser = argparse.ArgumentParser(prog="python3 build_docs.py")
    parser.add_argument("--check", action="store_true", help="only report stale pages")
    args = parser.parse_args()

    stale = []
    for path, text in pages().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.write_text(text, encoding="utf-8")
    verb = "Out of date" if args.check else "Wrote"
    print(f"{verb}: {', '.join(map(str, stale))}" if stale else "Docs are up to date.")
    sys.exit(1 if args.check and stale else 0)


if __name__ == "__main__":
    main()
